module.exports = [{
  model: 'Endpoint',
  documents: [{
    moduleName: 'module1',
    moduleInitTime: new Date(),
    systemTime: new Date(),
    queuesInsert: null,
    queuesInsertToProcess: null,
    queuesIn: null,
    queuesInToProcess: null,
    queuesOut: null,
    queuesOutV2: null,
    queuesError: null,
    queuesHealth: null,
    threadCount: 4,
    threadHealth: null,
    databaseHealth: null
  },{
    moduleName: 'module2',
    moduleInitTime: new Date(),
    systemTime: new Date(),
    queuesInsert: null,
    queuesInsertToProcess: null,
    queuesIn: null,
    queuesInToProcess: null,
    queuesOut: null,
    queuesOutV2: null,
    queuesError: null,
    queuesHealth: null,
    threadCount: 4,
    threadHealth: null,
    databaseHealth: null
  },{
    moduleName: 'module3',
    moduleInitTime: new Date(),
    systemTime: new Date(),
    queuesInsert: null,
    queuesInsertToProcess: null,
    queuesIn: null,
    queuesInToProcess: null,
    queuesOut: null,
    queuesOutV2: null,
    queuesError: null,
    queuesHealth: null,
    threadCount: 4,
    threadHealth: null,
    databaseHealth: null
  },{
    moduleName: 'module4',
    moduleInitTime: new Date(),
    systemTime: new Date(),
    queuesInsert: null,
    queuesInsertToProcess: null,
    queuesIn: null,
    queuesInToProcess: null,
    queuesOut: null,
    queuesOutV2: null,
    queuesError: null,
    queuesHealth: null,
    threadCount: 4,
    threadHealth: null,
    databaseHealth: null
  }]
}];
