module.exports = [{
  model: 'Endpoint',
  documents: [{
    moduleName: 'module1',
    moduleInitTime: new Date(),
    systemTime: new Date(),
    queuesInsert: null,
    queuesInsertToProcess: null,
    queuesIn: null,
    queuesInToProcess: null,
    queuesOut: null,
    queuesOutV2: null,
    queuesError: null,
    queuesHealth: null,
    threadCount: 4,
    threadHealth: null,
    databaseHealth: null
  },{
    moduleName: 'module2',
    moduleInitTime: new Date(),
    systemTime: new Date(),
    queuesInsert: null,
    queuesInsertToProcess: null,
    queuesIn: null,
    queuesInToProcess: null,
    queuesOut: null,
    queuesOutV2: null,
    queuesError: null,
    queuesHealth: null,
    threadCount: 4,
    threadHealth: null,
    databaseHealth: null
  },{
    moduleName: 'module3',
    moduleInitTime: new Date(),
    systemTime: new Date(),
    queuesInsert: null,
    queuesInsertToProcess: null,
    queuesIn: null,
    queuesInToProcess: null,
    queuesOut: null,
    queuesOutV2: null,
    queuesError: null,
    queuesHealth: null,
    threadCount: 4,
    threadHealth: null,
    databaseHealth: null
  },{
    moduleName: 'module4',
    moduleInitTime: new Date(),
    systemTime: new Date(),
    queuesInsert: null,
    queuesInsertToProcess: null,
    queuesIn: null,
    queuesInToProcess: null,
    queuesOut: null,
    queuesOutV2: null,
    queuesError: null,
    queuesHealth: null,
    threadCount: 4,
    threadHealth: null,
    databaseHealth: null
  }, {
    moduleName: 'module5',
    moduleInitTime: new Date(),
    systemTime: new Date(),
    queuesInsert: null,
    queuesInsertToProcess: null,
    queuesIn: null,
    queuesInToProcess: null,
    queuesOut: null,
    queuesOutV2: null,
    queuesError: null,
    queuesHealth: null,
    threadCount: 8,
    threadHealth: null,
    databaseHealth: null
  }, {
    moduleName: 'module6',
    moduleInitTime: new Date(),
    systemTime: new Date(),
    queuesInsert: null,
    queuesInsertToProcess: null,
    queuesIn: null,
    queuesInToProcess: null,
    queuesOut: null,
    queuesOutV2: null,
    queuesError: null,
    queuesHealth: null,
    threadCount: 8,
    threadHealth: null,
    databaseHealth: null
  }, {
    moduleName: 'module7',
    moduleInitTime: new Date(),
    systemTime: new Date(),
    queuesInsert: null,
    queuesInsertToProcess: null,
    queuesIn: null,
    queuesInToProcess: null,
    queuesOut: null,
    queuesOutV2: null,
    queuesError: null,
    queuesHealth: null,
    threadCount: 16,
    threadHealth: null,
    databaseHealth: null
  }, {
    moduleName: 'module8',
    moduleInitTime: new Date(),
    systemTime: new Date(),
    queuesInsert: null,
    queuesInsertToProcess: null,
    queuesIn: null,
    queuesInToProcess: null,
    queuesOut: null,
    queuesOutV2: null,
    queuesError: null,
    queuesHealth: null,
    threadCount: 16,
    threadHealth: null,
    databaseHealth: null
  }]
}];
